In [1]:
#dataset = https://www.kaggle.com/datasets/kandij/diabetes-dataset

#importing libraries:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
import kagglehub
from kagglehub import KaggleDatasetAdapter

In [2]:
#downloading data:
kagglehub.dataset_download('kandij/diabetes-dataset')

Downloading from https://www.kaggle.com/api/v1/datasets/download/kandij/diabetes-dataset?dataset_version_number=1...

100%|██████████| 8.92k/8.92k [00:00<?, ?B/s]

Extracting files...

'C:\\Users\\Lenovo\\.cache\\kagglehub\\datasets\\kandij\\diabetes-dataset\\versions\\1'

In [8]:
#importing data:
df = pd.read_csv(r'C:\\Users\\Lenovo\\.cache\\kagglehub\\datasets\\kandij\\diabetes-dataset\\versions\\1\diabetes2.csv')
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [9]:
#defining x and y:
x = df.drop(columns = ['Outcome'])
y = df['Outcome']

In [10]:
#splitting data for training and testing:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 42)

In [32]:
#creating an ai model:
model = LogisticRegression(max_iter = 500, class_weight = 'balanced')

In [33]:
#training ai model:
model.fit(x_train, y_train)

LogisticRegression(class_weight='balanced', max_iter=500)

In [34]:
#testing ai model based on testing data:
predictions = model.predict(x_test)

In [35]:
#showing predicted result:
pd.concat([x_test.reset_index(drop = True), y_test.reset_index(drop = True), pd.DataFrame(predictions, columns = ['Predictions'])], axis = 1)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,Predictions
0,6,98,58,33,190,34.0,0.430,43,0,0
1,2,112,75,32,0,35.7,0.148,21,0,0
2,2,108,64,0,0,30.8,0.158,21,0,0
3,8,107,80,0,0,24.6,0.856,34,0,0
4,7,136,90,0,0,29.9,0.210,50,0,1
...,...,...,...,...,...,...,...,...,...,...
226,0,119,0,0,0,32.4,0.141,24,1,0
227,4,109,64,44,99,34.8,0.905,26,1,0
228,0,127,80,37,210,36.3,0.804,23,0,0
229,6,105,70,32,68,30.8,0.122,37,0,0
230,5,77,82,41,42,35.8,0.156,35,0,0

In [36]:
#evaluating ai model:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.81      0.71      0.76       151
           1       0.56      0.69      0.61        80

    accuracy                           0.70       231
   macro avg       0.68      0.70      0.69       231
weighted avg       0.72      0.70      0.71       231

In [37]:
confusion_matrix(y_test, predictions)

array([[107,  44],
       [ 25,  55]])